### PR TITLE
Quality of life features

### PR DESCRIPTION
**Pull request by Roizor**
why do you always keep everything in 1 index.html? its much easier to spread it out

### CODE REVIEW

**Review by Roizor — COMMENTED** [review]
yep its good

**Comment by ni5arga** [comment]
Umm I see.

**Comment by ni5arga** [comment]
Let me review it up.

**Review by ni5arga — CHANGES_REQUESTED** [review]
1. Change the button colors to blue or the previous color.
2. Increase button length to previous.

**Comment by Roizor** [comment]
Im a bit confused by "change button colors to blue" because they are indeed still blue.

**Comment by ni5arga** [comment]
Change them to anything else, I don't like the present color.

**Comment by ni5arga** [comment]
They are blue when tapped, I want them to be blue without being tapped. And increase button length.

**Comment by Roizor** [comment]
Hey: I'm not sure how to change the button length because of the w3 css being used

**Comment by ni5arga** [comment]
Can't you turn them to the previous button length?

**Comment by ni5arga** [comment]
And fix the colors.

**Comment by ni5arga** [comment]
I'm working out rn, I'll merge your pr later.

**Pull request merged**
